{{- if or (not .Values.alembic.externalSecrets.enabled) (not .Values.alembic.enabled) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chartreuse.fullname" . }}
  labels:
    app: {{ template "chartreuse.name" . }}
    chart: {{ template "chartreuse.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
{{- if .Values.alembic.enabled }}
  CHARTREUSE_ALEMBIC_URL: {{ template "chartreuse.alembic.url" . }}
  PG_ISREADY_CHARTREUSE_ALEMBIC_URL: {{ .Values.chartreuse.pg_isready_chartreuse_alembic_url | default (template "chartreuse.alembic.url" . ) }}
{{- else }}
  CHARTREUSE_ALEMBIC_URL: ""
  PG_ISREADY_CHARTREUSE_ALEMBIC_URL: ""
{{- end }}
{{- end -}}
